### ISSUE TITLE
Вынести обработчики из main в отдельный модуль

### ISSUE THREAD

**Issue by learies** [Ninefiveblade/poetryfastblog#3]
Нужно из main вынести обработчики в отдельный модуль. Модуль можно назвать routs.py или handlers.py.

**Comment by Ninefiveblade** [comment]
Хорошая идея, можно назвать views.py как было привычно, думаю это более понятно будет для всех

**Comment by Ninefiveblade** [comment]
Предлагаю дальнейшие изменения делать в ветке develop, поскольку проект main достиг минимально рабочего проекта, дальше его можно только дополнять
